version: '3'

services:
    app:
        build: .
        volumes:
            - ./:/var/www
        depends_on:
            - app-mysql
    app-mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "./.docker/db:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: desafio
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    app-nginx:
        build: .docker/nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
        depends_on:
            - app
